### ISSUE TITLE
No module named 'parameters'

### ISSUE THREAD

**Issue by ggyyzm** [enzezhang/Front_DL3#1]
Dear @enzezhang  and all,
I'm a graduate student.
Please allows me to ask, should there be a file parameters.py in folder pytorch-deeplab-xception ?
I ran into the following problem when running exe_inference.sh file
`Traceback (most recent call last):
  File "/media/server123/747966f3-070a-42b3-af82-6edf8d1e1a93/zm/PycharmProjects/Front_DL3-master/pytorch-deeplab-xception/inference.py", line 25, in <module>
    import parameters
ModuleNotFoundError: No module named 'parameters'
cat: ./list/test.txt: No such file or directory
`
I have seen a file named "parameters.pyc". After I add the parameters.pyc file to the folder "pytorch-deeplab-sception", it becomes
`Traceback (most recent call last):
  File "/media/server123/747966f3-070a-42b3-af82-6edf8d1e1a93/zm/PycharmProjects/Front_DL3-master/pytorch-deeplab-xception/inference.py", line 25, in <module>
    import parameters
ImportError: bad magic number in 'parameters': b'\x03\xf3\r\n'
cat: ./list/test.txt: No such file or directory
`
Could you please help me with how to solve this problem
Thank you very much. :)

**Comment by enzezhang** [comment]
The parameters.py is in Front_DL3/script, just copy it to the folder pytorch-deeplab-xception. I will update the github code later.

Thanks for your question.

**Comment by ggyyzm** [comment]
> The parameters.py is in Front_DL3/script, just copy it to the folder pytorch-deeplab-xception. I will update the github code later.
> 
> Thanks for your question.

I apologize for my oversight. Thank you for your reply!
